- id: perlcritic
  name: perlcritic
  description: Perl source code critic (native install)
  language: perl
  additional_dependencies: [PETDANCE/Perl-Critic-1.146.tar.gz]
  entry: perlcritic
  args: [--quiet]
  types: [perl]
  stages: [commit, merge-commit, push, manual]
