- id: perlcritic
  name: perlcritic
  description: Perl source code critic (native install)
  language: perl
  additional_dependencies: [PETDANCE/Perl-Critic-1.156.tar.gz]
  entry: perlcritic
  args: [--quiet]
  types: [perl]
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
  minimum_pre_commit_version: 3.2.0 # for "stages" names
